### ISSUE TITLE
Ask to join the group

### ISSUE THREAD

**Issue by ozbillwang** [terraform-community-modules/tf_aws_rds#20]
@solarce 
@antonbabenko 
@hakamadare 

Not sure how to contact you and the group owner of `terraform-community-modules`. I am using terraform every day for last 2 years and want to join the group to help.

**Comment by antonbabenko** [comment]
@ozbillwang The best way to get `write` permissions is to contribute to specific repositories several times (you have done it) and to request permissions (normally via email, my email is on my GitHub profile page, for example).

PS: You should have received an invitation by email.

PPS: Do you still want to provide Azure DB Terraform module? If so, what repository name do you have in mind for it?
