### ISSUE TITLE
database subnet group

### ISSUE THREAD

**Issue by ozbillwang** [terraform-community-modules/tf_aws_rds#23]
@antonbabenko 

I found database subnet group is created in both modules (tf_aws_vpc and tf_aws_rds). 

Should we remove ours? So any databases in that VPC will share the same subnet group, it looks neat.

**Comment by antonbabenko** [comment]
Both of these modules as well as any other can be used independently, so I don't see a reason why we should remove database security group from any of those.

**Comment by ozbillwang** [comment]
I think the module owners should work together, seems not. 

Thats' fine, not big deal.

**Comment by antonbabenko** [comment]
The way how Terraform community modules are created and used is that they have no dependencies between themselves. It is always optional to use any of these modules alone or in any combination.
