### ISSUE TITLE
Setting aws_db_parameter_group per RDS instance

### ISSUE THREAD

**Issue by gstlt** [terraform-community-modules/tf_aws_rds#29]
Hey all!
I've been bumping against this for some time now and haven't found any satisfying solution.

I'm running several RDS instances (Postgres and MySQL). Default parameter group settings were fine until now. I'd like to override some settings on one of the RDS instance, but all my instances are being managed by tf_aws_rds module, so if I add some parameter to module, all my instances will be altered. Which of course I don't want to do.

Do you have any ideas or working solutions on that?

Thanks a lot!
Grzegorz

**Comment by antonbabenko** [comment]
Good point. You are right, it is not possible to provide parameter group settings to the module at the moment.

As a solution, we can extend this module to create parameter group conditionally, or use the one passed to it.

**Comment by hakamadare** [comment]
@gstlt my first thought is to have our module create a parameter group for each database; in my production operations i don't use the default parameter group for anything. 

i'm planning on doing some work on this module soon to add support for read replicas, i can try to add this feature request at the same time.

**Comment by gstlt** [comment]
@antonbabenko Passing parameter group to the module sounds like an idea. :)

@hakamadare Thanks! I won't have time to deal with this at the moment, so that would be great if it's not too big of a trouble.

I guess for now I'll be using suggestion from @antonbabenko. I'll share when our team will implement something useful.

Cheers!
Grzegorz
