### ISSUE TITLE
hardcoded aws variables used

### ISSUE THREAD

**Issue by Morriz** [terraform-community-modules/tf_aws_rds#6]
Please don't include the

```
provider "aws" { ... }
```

block, as it forces the user to specify those values from a var, and the default mechanism (cli>env>creds etc) will thus not be used. See https://groups.google.com/d/msg/terraform-tool/e9eIdaPE1p0/pPMPxEmACgAJ

**Comment by gstlt** [comment]
This should be fixed after merging that PR: https://github.com/terraform-community-modules/tf_aws_rds/pull/8

**Comment by antonbabenko** [comment]
Thanks @gstlt

**Comment by gstlt** [comment]
Happy to help :-)
